-- Aggregate extract for loyalty-burden-atlas.html.
-- Save the result grid as loyalty_landscape.csv with column headers.
-- No patient identifiers are returned. Cells smaller than @MIN_CELL_SIZE
-- are omitted; use the disclosure threshold required by your institution.

SET NOCOUNT ON;

DECLARE @SITE varchar(100) = NULL;        -- NULL = all sites
DECLARE @COHORT_NAME varchar(100) = NULL; -- NULL = all cohorts
DECLARE @LOOKBACK_YEARS int = NULL;       -- NULL = all lookbacks
DECLARE @GENDERED char(1) = NULL;         -- NULL = both Y and N runs
DECLARE @MIN_CELL_SIZE int = 10;

;WITH MATCHED AS (
  SELECT
    R.SITE,
    R.COHORT_NAME,
    R.LOOKBACK_YEARS,
    R.GENDER_DENOMINATORS_YN,
    R.PATIENT_NUM,
    COALESCE(NULLIF(R.AGE_GRP, ''), 'Unknown') AS AGE_GRP,
    COALESCE(NULLIF(R.SEX, ''), 'Unknown') AS SEX,
    R.PREDICTED_SCORE,
    COALESCE(C.CHARLSON_INDEX, 0) AS CHARLSON_INDEX,
    C.CHARLSON_10YR_PROB,
    R.NUM_DX1, R.NUM_DX2, R.MED_USE1, R.MED_USE2,
    R.MAMMOGRAPHY, R.PAP_TEST, R.PSA_TEST, R.COLONOSCOPY,
    R.FECAL_OCCULT_TEST, R.FLU_SHOT, R.PNEUMOCOCCAL_VACCINE,
    R.BMI, R.A1C, R.MEDICAL_EXAM,
    R.INP1_OPT1_VISIT, R.OPT2_VISIT, R.ED_VISIT,
    R.MDVISIT_PNAME2, R.MDVISIT_PNAME3, R.ROUTINE_CARE_2
  FROM dbo.DT_LOYALTY_RESULT R
  JOIN dbo.DT_LOYALTY_RESULT_CHARLSON C
    ON C.SITE = R.SITE
   AND C.COHORT_NAME = R.COHORT_NAME
   AND C.PATIENT_NUM = R.PATIENT_NUM
   AND C.LOOKBACK_YEARS = R.LOOKBACK_YEARS
   AND C.GENDER_DENOMINATORS_YN = R.GENDER_DENOMINATORS_YN
  WHERE (@SITE IS NULL OR R.SITE = @SITE)
    AND (@COHORT_NAME IS NULL OR R.COHORT_NAME = @COHORT_NAME)
    AND (@LOOKBACK_YEARS IS NULL OR R.LOOKBACK_YEARS = @LOOKBACK_YEARS)
    AND (@GENDERED IS NULL OR R.GENDER_DENOMINATORS_YN = @GENDERED)
), SCORED AS (
  SELECT *,
    NTILE(10) OVER (
      PARTITION BY SITE, COHORT_NAME, LOOKBACK_YEARS, GENDER_DENOMINATORS_YN
      ORDER BY PREDICTED_SCORE, PATIENT_NUM
    ) AS LOYALTY_DECILE,
    CASE
      WHEN CHARLSON_INDEX = 0 THEN '0'
      WHEN CHARLSON_INDEX = 1 THEN '1'
      WHEN CHARLSON_INDEX = 2 THEN '2'
      WHEN CHARLSON_INDEX BETWEEN 3 AND 4 THEN '3-4'
      ELSE '5+'
    END AS CHARLSON_BAND
  FROM MATCHED
), AGGREGATED AS (
  SELECT
    SITE, COHORT_NAME, LOOKBACK_YEARS, GENDER_DENOMINATORS_YN,
    AGE_GRP, SEX, LOYALTY_DECILE, CHARLSON_BAND,
    COUNT_BIG(*) AS PATIENT_COUNT,
    AVG(CONVERT(float, PREDICTED_SCORE)) AS MEAN_LOYALTY_SCORE,
    AVG(CONVERT(float, CHARLSON_INDEX)) AS MEAN_CHARLSON_INDEX,
    AVG(CONVERT(float, CHARLSON_10YR_PROB)) AS MEAN_CHARLSON_10YR_PROB,
    SUM(CONVERT(bigint, NUM_DX1)) AS NUM_DX1_COUNT,
    SUM(CONVERT(bigint, NUM_DX2)) AS NUM_DX2_COUNT,
    SUM(CONVERT(bigint, MED_USE1)) AS MED_USE1_COUNT,
    SUM(CONVERT(bigint, MED_USE2)) AS MED_USE2_COUNT,
    SUM(CONVERT(bigint, MAMMOGRAPHY)) AS MAMMOGRAPHY_COUNT,
    SUM(CONVERT(bigint, PAP_TEST)) AS PAP_TEST_COUNT,
    SUM(CONVERT(bigint, PSA_TEST)) AS PSA_TEST_COUNT,
    SUM(CONVERT(bigint, COLONOSCOPY)) AS COLONOSCOPY_COUNT,
    SUM(CONVERT(bigint, FECAL_OCCULT_TEST)) AS FECAL_OCCULT_TEST_COUNT,
    SUM(CONVERT(bigint, FLU_SHOT)) AS FLU_SHOT_COUNT,
    SUM(CONVERT(bigint, PNEUMOCOCCAL_VACCINE)) AS PNEUMOCOCCAL_VACCINE_COUNT,
    SUM(CONVERT(bigint, BMI)) AS BMI_COUNT,
    SUM(CONVERT(bigint, A1C)) AS A1C_COUNT,
    SUM(CONVERT(bigint, MEDICAL_EXAM)) AS MEDICAL_EXAM_COUNT,
    SUM(CONVERT(bigint, INP1_OPT1_VISIT)) AS INP1_OPT1_VISIT_COUNT,
    SUM(CONVERT(bigint, OPT2_VISIT)) AS OPT2_VISIT_COUNT,
    SUM(CONVERT(bigint, ED_VISIT)) AS ED_VISIT_COUNT,
    SUM(CONVERT(bigint, MDVISIT_PNAME2)) AS MDVISIT_PNAME2_COUNT,
    SUM(CONVERT(bigint, MDVISIT_PNAME3)) AS MDVISIT_PNAME3_COUNT,
    SUM(CONVERT(bigint, ROUTINE_CARE_2)) AS ROUTINE_CARE_2_COUNT
  FROM SCORED
  GROUP BY SITE, COHORT_NAME, LOOKBACK_YEARS, GENDER_DENOMINATORS_YN,
    AGE_GRP, SEX, LOYALTY_DECILE, CHARLSON_BAND
)
SELECT *
FROM AGGREGATED
WHERE PATIENT_COUNT >= @MIN_CELL_SIZE
ORDER BY SITE, COHORT_NAME, LOOKBACK_YEARS, GENDER_DENOMINATORS_YN,
  AGE_GRP, SEX, LOYALTY_DECILE,
  CASE CHARLSON_BAND WHEN '0' THEN 0 WHEN '1' THEN 1 WHEN '2' THEN 2
    WHEN '3-4' THEN 3 ELSE 4 END;

