-- Aggregate Charlson-condition extract for loyalty-burden-atlas.html.
-- Save the result grid as charlson_profile.csv with column headers.
-- No patient identifiers are returned. Groups smaller than @MIN_CELL_SIZE
-- are omitted; use the disclosure threshold required by your institution.

SET NOCOUNT ON;

DECLARE @SITE varchar(100) = NULL;        -- NULL = all sites
DECLARE @COHORT_NAME varchar(100) = NULL; -- NULL = all cohorts
DECLARE @LOOKBACK_YEARS int = NULL;       -- NULL = all lookbacks
DECLARE @GENDERED char(1) = NULL;         -- NULL = both Y and N runs
DECLARE @MIN_CELL_SIZE int = 10;

;WITH MATCHED AS (
  SELECT
    R.SITE,
    R.COHORT_NAME,
    R.LOOKBACK_YEARS,
    R.GENDER_DENOMINATORS_YN,
    R.PATIENT_NUM,
    COALESCE(NULLIF(R.AGE_GRP, ''), 'Unknown') AS AGE_GRP,
    COALESCE(NULLIF(R.SEX, ''), 'Unknown') AS SEX,
    R.PREDICTED_SCORE,
    C.MI, C.CHF, C.CVD, C.PVD, C.DEMENTIA, C.COPD, C.RHEUMDIS,
    C.PEPULCER, C.MILDLIVDIS, C.DIABETES_NOCC, C.DIABETES_WTCC,
    C.HEMIPARAPLEG, C.RENALDIS, C.CANCER, C.MSVLIVDIS,
    C.METASTATIC, C.AIDSHIV
  FROM dbo.DT_LOYALTY_RESULT R
  JOIN dbo.DT_LOYALTY_RESULT_CHARLSON C
    ON C.SITE = R.SITE
   AND C.COHORT_NAME = R.COHORT_NAME
   AND C.PATIENT_NUM = R.PATIENT_NUM
   AND C.LOOKBACK_YEARS = R.LOOKBACK_YEARS
   AND C.GENDER_DENOMINATORS_YN = R.GENDER_DENOMINATORS_YN
  WHERE (@SITE IS NULL OR R.SITE = @SITE)
    AND (@COHORT_NAME IS NULL OR R.COHORT_NAME = @COHORT_NAME)
    AND (@LOOKBACK_YEARS IS NULL OR R.LOOKBACK_YEARS = @LOOKBACK_YEARS)
    AND (@GENDERED IS NULL OR R.GENDER_DENOMINATORS_YN = @GENDERED)
), TIERED AS (
  SELECT *,
    NTILE(3) OVER (
      PARTITION BY SITE, COHORT_NAME, LOOKBACK_YEARS, GENDER_DENOMINATORS_YN
      ORDER BY PREDICTED_SCORE, PATIENT_NUM
    ) AS LOYALTY_TIER_NUMBER
  FROM MATCHED
), LONG_FORM AS (
  SELECT
    SITE, COHORT_NAME, LOOKBACK_YEARS, GENDER_DENOMINATORS_YN,
    AGE_GRP, SEX,
    CASE LOYALTY_TIER_NUMBER WHEN 1 THEN 'Lower' WHEN 2 THEN 'Middle' ELSE 'Upper' END AS LOYALTY_GROUP,
    V.CHARLSON_CATEGORY,
    CASE WHEN COALESCE(V.WEIGHT, 0) > 0 THEN 1 ELSE 0 END AS HAS_CONDITION
  FROM TIERED
  CROSS APPLY (VALUES
    ('Myocardial infarction', MI),
    ('Congestive heart failure', CHF),
    ('Cerebrovascular disease', CVD),
    ('Peripheral vascular disease', PVD),
    ('Dementia', DEMENTIA),
    ('Chronic pulmonary disease', COPD),
    ('Rheumatic disease', RHEUMDIS),
    ('Peptic ulcer disease', PEPULCER),
    ('Mild liver disease', MILDLIVDIS),
    ('Diabetes without complications', DIABETES_NOCC),
    ('Diabetes with complications', DIABETES_WTCC),
    ('Hemiplegia or paraplegia', HEMIPARAPLEG),
    ('Renal disease', RENALDIS),
    ('Cancer', CANCER),
    ('Moderate or severe liver disease', MSVLIVDIS),
    ('Metastatic cancer', METASTATIC),
    ('AIDS/HIV', AIDSHIV)
  ) V(CHARLSON_CATEGORY, WEIGHT)
), AGGREGATED AS (
  SELECT
    SITE, COHORT_NAME, LOOKBACK_YEARS, GENDER_DENOMINATORS_YN,
    AGE_GRP, SEX, LOYALTY_GROUP, CHARLSON_CATEGORY,
    COUNT_BIG(*) AS PATIENT_COUNT,
    SUM(CONVERT(bigint, HAS_CONDITION)) AS CONDITION_COUNT,
    100.0 * SUM(CONVERT(float, HAS_CONDITION)) / NULLIF(COUNT_BIG(*), 0) AS PREVALENCE_PERCENT
  FROM LONG_FORM
  GROUP BY SITE, COHORT_NAME, LOOKBACK_YEARS, GENDER_DENOMINATORS_YN,
    AGE_GRP, SEX, LOYALTY_GROUP, CHARLSON_CATEGORY
)
SELECT *
FROM AGGREGATED
WHERE PATIENT_COUNT >= @MIN_CELL_SIZE
ORDER BY SITE, COHORT_NAME, LOOKBACK_YEARS, GENDER_DENOMINATORS_YN,
  AGE_GRP, SEX, CHARLSON_CATEGORY,
  CASE LOYALTY_GROUP WHEN 'Lower' THEN 1 WHEN 'Middle' THEN 2 ELSE 3 END;

