/*********************************************************
*           SQL SERVER SCRIPT TO CREATE DATA TABLES 
*            FOR "DIGITAL TWIN" DERIVED FACT TOOLS
*               Last updated 03/2024
**********************************************************/

/*********************************************************
*           LOYALTY COHORT - See this publication:
* Klann JG, Henderson DW, Morris M, et al. A broadly applicable approach to enrich 
* electronic-health-record cohorts by identifying patients with complete data: a 
* multisite evaluation. J Am Med Inform Assoc Published Online First: 25 August 2023. 
* doi:10.1093/jamia/ocad166
**********************************************************/



CREATE TABLE [DBO].[DT_LOYALTY_PATHS]( -- Was DT_LOYALTY_PATHS
	[FEATURE_NAME] [VARCHAR](50) NULL,
	[CODE_TYPE] [VARCHAR](50) NULL,
	[CONCEPT_PATH] [VARCHAR](500) NULL,
	[SITE_SPECIFIC_CODE] [VARCHAR](10) NULL,
	[COMMENT] [VARCHAR](250) NULL,
) ON [PRIMARY];

CREATE CLUSTERED INDEX [NDX_PATH] ON [DBO].[DT_LOYALTY_PATHS]
(
	[CONCEPT_PATH] ASC,
	[FEATURE_NAME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON);

SET ANSI_PADDING OFF;


CREATE TABLE [DBO].[DT_LOYALTY_CHARLSON]( -- Was DT_LOYALTY_CHARLSON
	[CHARLSON_CATGRY] [varchar](50) NULL,
	[CHARLSON_WT] INT NULL,
	[DIAGPATTERN] [varchar](50) NULL
) ON [PRIMARY];

CREATE TABLE [DBO].[DT_LOYALTY_PSCOEFF] ( -- Was DT_LOYALTY_PSCOEFF
  FIELD_NAME VARCHAR(50),
  COEFF NUMERIC(4,3)
);

  CREATE TABLE DBO.[DT_LOYALTY_RESULT_SUMMARY](
    [COHORT_NAME] VARCHAR(100) NOT NULL,
    [SITE] VARCHAR(10) NOT NULL,
    [GENDER_DENOMINATORS_YN] CHAR(1) NOT NULL,
    [CUTOFF_FILTER_YN] CHAR(1) NOT NULL,
    [SUMMARY_DESCRIPTION] VARCHAR(20) NOT NULL,
	  [TABLE_NAME] [VARCHAR](20) NULL,
	  [NUM_DX1] FLOAT NULL,
	  [NUM_DX2] FLOAT NULL,
	  [MED_USE1] FLOAT NULL,
	  [MED_USE2] FLOAT NULL,
	  [MAMMOGRAPHY] FLOAT NULL,
	  [PAP_TEST] FLOAT NULL,
	  [PSA_TEST] FLOAT NULL,
	  [COLONOSCOPY] FLOAT NULL,
	  [FECAL_OCCULT_TEST] FLOAT NULL,
	  [FLU_SHOT] FLOAT NULL,
	  [PNEUMOCOCCAL_VACCINE] FLOAT NULL,
	  [BMI] FLOAT NULL,
	  [A1C] FLOAT NULL,
	  [MEDICAL_EXAM] FLOAT NULL,
	  [INP1_OPT1_VISIT] FLOAT NULL,
	  [OPT2_VISIT] FLOAT NULL,
	  [ED_VISIT] FLOAT NULL,
	  [MDVISIT_PNAME2] FLOAT NULL,
	  [MDVISIT_PNAME3] FLOAT NULL,
	  [ROUTINE_CARE_2] FLOAT NULL,
	  [SUBJECTS_NOCRITERIA] FLOAT NULL,
	  [PREDICTIVE_SCORE_CUTOFF] FLOAT NULL,
	  [MEAN_10YR_PROB] FLOAT NULL,
	  [MEDIAN_10YR_PROB] FLOAT NULL,
	  [MODE_10YR_PROB] FLOAT NULL,
	  [STDEV_10YR_PROB] FLOAT NULL,
    [TOTAL_SUBJECTS] INT NULL,
    [TOTAL_SUBJECTS_FEMALE] INT NULL,
    [TOTAL_SUBJECTS_MALE] INT NULL,
    [PERCENT_POPULATION] FLOAT NULL,
    [PERCENT_SUBJECTS_FEMALE] FLOAT NULL,
    [PERCENT_SUBJECTS_MALE] FLOAT NULL,
    [AVERAGE_FACT_COUNT] FLOAT NULL,
    [EXTRACT_DTTM] DATETIME NOT NULL DEFAULT GETDATE(),
    [LOOKBACK_YR] INT NOT NULL,
    [RUNTIME_MS] INT NULL
  );

  CREATE TABLE [DBO].[DT_LOYALTY_RESULT](
	  [LOOKBACK_YEARS] [INT] NOT NULL,
	  [GENDER_DENOMINATORS_YN] [CHAR](1) NOT NULL,
	  [SITE] [VARCHAR](100) NOT NULL,
	  [COHORT_NAME] [VARCHAR](100) NOT NULL,
	  [PATIENT_NUM] [INT] NOT NULL,
    [DEATH_DT] DATE NULL, /* ADDED OCT2022 */
	  [INDEX_DT] [DATE] NULL,
	  [SEX] [VARCHAR](50) NULL,
	  [AGE] [INT] NULL,
	  [AGE_GRP] [VARCHAR](20) NULL,
	  [NUM_DX1] [BIT] NOT NULL,
	  [NUM_DX2] [BIT] NOT NULL,
	  [MED_USE1] [BIT] NOT NULL,
	  [MED_USE2] [BIT] NOT NULL,
	  [MAMMOGRAPHY] [BIT] NOT NULL,
	  [PAP_TEST] [BIT] NOT NULL,
	  [PSA_TEST] [BIT] NOT NULL,
	  [COLONOSCOPY] [BIT] NOT NULL,
	  [FECAL_OCCULT_TEST] [BIT] NOT NULL,
	  [FLU_SHOT] [BIT] NOT NULL,
	  [PNEUMOCOCCAL_VACCINE] [BIT] NOT NULL,
	  [BMI] [BIT] NOT NULL,
	  [A1C] [BIT] NOT NULL,
	  [MEDICAL_EXAM] [BIT] NOT NULL,
	  [INP1_OPT1_VISIT] [BIT] NOT NULL,
	  [OPT2_VISIT] [BIT] NOT NULL,
	  [ED_VISIT] [BIT] NOT NULL,
	  [MDVISIT_PNAME2] [BIT] NOT NULL,
	  [MDVISIT_PNAME3] [BIT] NOT NULL,
	  [ROUTINE_CARE_2] [BIT] NOT NULL,
	  [PREDICTED_SCORE] [FLOAT] NOT NULL
  );
  
  CREATE TABLE [DBO].[DT_LOYALTY_RESULT_CHARLSON](
	  [LOOKBACK_YEARS] [INT] NULL,
	  [GENDER_DENOMINATORS_YN] [CHAR](1) NULL,
	  [SITE] [VARCHAR](100) NULL,
	  [COHORT_NAME] [VARCHAR](100) NOT NULL,
	  [PATIENT_NUM] [INT] NOT NULL,
    [DEATH_DT] DATE NULL, /* ADDED OCT2022 */
	  [LAST_VISIT] [DATE] NULL,
    [SEX] [VARCHAR](50) NULL,
	  [AGE] [INT] NULL,
	  [AGE_GRP] [VARCHAR](20) NULL,
	  [CHARLSON_INDEX] [INT] NULL,
	  [CHARLSON_10YR_PROB] [NUMERIC](10, 4) NULL,
	  [MI] [INT] NULL,
	  [CHF] [INT] NULL,
	  [CVD] [INT] NULL,
	  [PVD] [INT] NULL,
	  [DEMENTIA] [INT] NULL,
	  [COPD] [INT] NULL,
	  [RHEUMDIS] [INT] NULL,
	  [PEPULCER] [INT] NULL,
	  [MILDLIVDIS] [INT] NULL,
	  [DIABETES_NOCC] [INT] NULL,
	  [DIABETES_WTCC] [INT] NULL,
	  [HEMIPARAPLEG] [INT] NULL,
	  [RENALDIS] [INT] NULL,
	  [CANCER] [INT] NULL,
	  [MSVLIVDIS] [INT] NULL,
	  [METASTATIC] [INT] NULL,
	  [AIDSHIV] [INT] NULL
  );
  
CREATE TYPE DBO.UDT_DT_LOYALTY_COHORTFILTER AS TABLE (PATIENT_NUM INT, COHORT_NAME VARCHAR(100), INDEX_DT DATE);

-- Externally validated coefficients
INSERT INTO DT_LOYALTY_PSCOEFF (FIELD_NAME, COEFF)
VALUES ('MDVISIT_PNAME2',0.049)
,('MDVISIT_PNAME3',0.087)
,('MEDICAL_EXAM',0.078)
,('MAMMOGRAPHY',0.075)
,('PAP_TEST',0.009)
,('PSA_TEST',0.103)
,('COLONOSCOPY',0.064)
,('FECAL_OCCULT_TEST',0.034)
,('FLU_SHOT',0.102)
,('PNEUMOCOCCAL_VACCINE',0.031)
,('BMI',0.017)
,('A1C',0.018)
,('MED_USE1',0.002)
,('MED_USE2',0.074)
,('INP1_OPT1_VISIT',0.091)
,('OPT2_VISIT',0.050)
,('NUM_DX1',-0.026)
,('NUM_DX2',0.037)
,('ED_VISIT',0.078)
,('ROUTINE_CARE_2',0.049);

